/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kibana_ingestion;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        IngestionService classUnderTest = new IngestionService();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
